version: '3.4'

services:
  database:
    image: 'postgres:latest'
    ports:
      - 3001:5432
    environment:
      POSTGRES_USER: postgres # The PostgreSQL user (useful to connect to the database)
      POSTGRES_PASSWORD: postgres # The PostgreSQL password (useful to connect to the database)
      POSTGRES_DB: dejamobile # The PostgreSQL default database (automatically created at first launch)
  dejamobile:
    image: dejamobile
    depends_on:
      - database
    build: .
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
